title: Zhiyang Zhou
description: Zhiyang Zhou's Homepage
remote_theme: just-the-docs/just-the-docs

url: "https://zhiyanggeezhou.github.io"
  
color_scheme: light

search_enabled: false
heading_anchors: true

aux_links:
  GitHub:
    - "https://github.com/ZhiyangGeeZhou"
  CV:
    - "/attach/CV20260324.pdf"

plugins:
  - jekyll-remote-theme
  
just_the_docs:
  custom_css:
    - assets/css/custom.css
